//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.HelloService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloService.IHelloService")]
    public interface IHelloService {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IHelloService/GetMessageWithoutAnyProtection", ReplyAction="http://tempuri.org/IHelloService/GetMessageWithoutAnyProtectionResponse")]
        string GetMessageWithoutAnyProtection();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IHelloService/GetMessageWithoutAnyProtection", ReplyAction="http://tempuri.org/IHelloService/GetMessageWithoutAnyProtectionResponse")]
        System.Threading.Tasks.Task<string> GetMessageWithoutAnyProtectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://tempuri.org/IHelloService/GetSignedMessage", ReplyAction="http://tempuri.org/IHelloService/GetSignedMessageResponse")]
        string GetSignedMessage();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://tempuri.org/IHelloService/GetSignedMessage", ReplyAction="http://tempuri.org/IHelloService/GetSignedMessageResponse")]
        System.Threading.Tasks.Task<string> GetSignedMessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IHelloService/GetSignedMessageAndEncrypted", ReplyAction="http://tempuri.org/IHelloService/GetSignedMessageAndEncryptedResponse")]
        string GetSignedMessageAndEncrypted();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IHelloService/GetSignedMessageAndEncrypted", ReplyAction="http://tempuri.org/IHelloService/GetSignedMessageAndEncryptedResponse")]
        System.Threading.Tasks.Task<string> GetSignedMessageAndEncryptedAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloServiceChannel : Client.HelloService.IHelloService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloServiceClient : System.ServiceModel.ClientBase<Client.HelloService.IHelloService>, Client.HelloService.IHelloService {
        
        public HelloServiceClient() {
        }
        
        public HelloServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMessageWithoutAnyProtection() {
            return base.Channel.GetMessageWithoutAnyProtection();
        }
        
        public System.Threading.Tasks.Task<string> GetMessageWithoutAnyProtectionAsync() {
            return base.Channel.GetMessageWithoutAnyProtectionAsync();
        }
        
        public string GetSignedMessage() {
            return base.Channel.GetSignedMessage();
        }
        
        public System.Threading.Tasks.Task<string> GetSignedMessageAsync() {
            return base.Channel.GetSignedMessageAsync();
        }
        
        public string GetSignedMessageAndEncrypted() {
            return base.Channel.GetSignedMessageAndEncrypted();
        }
        
        public System.Threading.Tasks.Task<string> GetSignedMessageAndEncryptedAsync() {
            return base.Channel.GetSignedMessageAndEncryptedAsync();
        }
    }
}
